[package]
name = "rust-sudoku"
version = "0.1.0"
edition = "2021"


[dev-dependencies]

pretty_assertions = { version = "1.2", features = ["alloc"], default-features = false }

[dependencies]
eframe = "0.22.0"
